#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$branch" != "main" ]]; then
	exit 0
fi

echo "building wasmJs(takes 2 min or so.)"
./gradlew wasmJsBrowserDistribution
wasmJsStatus=$?
if [ $wasmJsStatus -ne 0 ]; then
	echo "wasmJs build failed"
	exit 1
fi

echo "Running All KMP Tests"
./gradlew alltests
testsStatus=$?
if [ $testsStatus -ne 0 ]; then
	echo "tests failed"
	exit 1
fi

./gradlew assembleDebug
buildStatus=$?
if [ $buildStatus -ne 0 ]; then
	echo "build filed"
	exit 1
fi

echo "looks good! Ship it!"
exit 0
