# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache.problems=warn
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.newDsl=true
android.builtInKotlin=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.experimental.enableScreenshotTest=true
deeplink.scheme=https
deeplink.host=develsinthedetails.codeberg.page
deeplink.play=/play
deeplink.draw=/draw
deeplink.sentence=/sentence
deeplink.previousGames=/previous_games
deeplink.previousGameDetails=/previous_game_details
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
