import android.content.res.Configuration
import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview
import com.android.tools.screenshot.PreviewTest
import dev.develsinthedetails.eatpoopyoucat.feature.draw.DrawingWithSentencePreview
import dev.develsinthedetails.eatpoopyoucat.feature.setup.HomeScreenPreview
import dev.develsinthedetails.eatpoopyoucat.feature.sentence.SentenceScreenPreview
import dev.develsinthedetails.eatpoopyoucat.feature.sentence.SentenceScreenWithDrawingPreview
import dev.develsinthedetails.eatpoopyoucat.core.ui.theme.AppTheme

@PreviewTest
@Preview(name = "1_en-US_Light_phoneScreenshots")
@Preview(name = "1_en-US_Dark_phoneScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_en-US_Light_sevenInchScreenshots", device = "id:Nexus 7")
@Preview(name = "1_en-US_Dark_sevenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_en-US_Light_tenInchScreenshots", device = "id:pixel_tablet")
@Preview(name = "1_en-US_Dark_tenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_de-DE_Light_phoneScreenshots", locale = "de")
@Preview(name = "1_de-DE_Dark_phoneScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_de-DE_Light_sevenInchScreenshots", locale = "de", device = "id:Nexus 7")
@Preview(name = "1_de-DE_Dark_sevenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_de-DE_Light_tenInchScreenshots", locale = "de", device = "id:pixel_tablet")
@Preview(name = "1_de-DE_Dark_tenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_fr-FR_Light_phoneScreenshots", locale = "fr")
@Preview(name = "1_fr-FR_Dark_phoneScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_fr-FR_Light_sevenInchScreenshots", locale = "fr", device = "id:Nexus 7")
@Preview(name = "1_fr-FR_Dark_sevenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_fr-FR_Light_tenInchScreenshots", locale = "fr", device = "id:pixel_tablet")
@Preview(name = "1_fr-FR_Dark_tenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_ja-JP_Light_phoneScreenshots", locale = "ja")
@Preview(name = "1_ja-JP_Dark_phoneScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_ja-JP_Light_sevenInchScreenshots", locale = "ja", device = "id:Nexus 7")
@Preview(name = "1_ja-JP_Dark_sevenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_ja-JP_Light_tenInchScreenshots", locale = "ja", device = "id:pixel_tablet")
@Preview(name = "1_ja-JP_Dark_tenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_pt_Light_phoneScreenshots", locale = "pt")
@Preview(name = "1_pt_Dark_phoneScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_pt_Light_sevenInchScreenshots", locale = "pt", device = "id:Nexus 7")
@Preview(name = "1_pt_Dark_sevenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_pt_Light_tenInchScreenshots", locale = "pt", device = "id:pixel_tablet")
@Preview(name = "1_pt_Dark_tenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_ta_Light_phoneScreenshots", locale = "ta")
@Preview(name = "1_ta_Dark_phoneScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_ta_Light_sevenInchScreenshots", locale = "ta", device = "id:Nexus 7")
@Preview(name = "1_ta_Dark_sevenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_ta_Light_tenInchScreenshots", locale = "ta", device = "id:pixel_tablet")
@Preview(name = "1_ta_Dark_tenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_tr-TR_Light_phoneScreenshots", locale = "tr")
@Preview(name = "1_tr-TR_Dark_phoneScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_tr-TR_Light_sevenInchScreenshots", locale = "tr", device = "id:Nexus 7")
@Preview(name = "1_tr-TR_Dark_sevenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_tr-TR_Light_tenInchScreenshots", locale = "tr", device = "id:pixel_tablet")
@Preview(name = "1_tr-TR_Dark_tenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_uk_Light_phoneScreenshots", locale = "uk")
@Preview(name = "1_uk_Dark_phoneScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_uk_Light_sevenInchScreenshots", locale = "uk", device = "id:Nexus 7")
@Preview(name = "1_uk_Dark_sevenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_uk_Light_tenInchScreenshots", locale = "uk", device = "id:pixel_tablet")
@Preview(name = "1_uk_Dark_tenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "1_zh-CN_Light_phoneScreenshots", locale = "zh-CN")
@Preview(name = "1_zh-CN_Dark_phoneScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "1_zh-CN_Light_sevenInchScreenshots", locale = "zh-CN", device = "id:Nexus 7")
@Preview(name = "1_zh-CN_Dark_sevenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "1_zh-CN_Light_tenInchScreenshots", locale = "zh-CN", device = "id:pixel_tablet")
@Preview(name = "1_zh-CN_Dark_tenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Composable
fun TakePreviewHomeScreenScreenShots() {
    AppTheme {
        HomeScreenPreview()
    }
}

@PreviewTest
@Preview(name = "2_en-US_Light_phoneScreenshots")
@Preview(name = "2_en-US_Dark_phoneScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_en-US_Light_sevenInchScreenshots", device = "id:Nexus 7")
@Preview(name = "2_en-US_Dark_sevenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_en-US_Light_tenInchScreenshots", device = "id:pixel_tablet")
@Preview(name = "2_en-US_Dark_tenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_de-DE_Light_phoneScreenshots", locale = "de")
@Preview(name = "2_de-DE_Dark_phoneScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_de-DE_Light_sevenInchScreenshots", locale = "de", device = "id:Nexus 7")
@Preview(name = "2_de-DE_Dark_sevenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_de-DE_Light_tenInchScreenshots", locale = "de", device = "id:pixel_tablet")
@Preview(name = "2_de-DE_Dark_tenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_fr-FR_Light_phoneScreenshots", locale = "fr")
@Preview(name = "2_fr-FR_Dark_phoneScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_fr-FR_Light_sevenInchScreenshots", locale = "fr", device = "id:Nexus 7")
@Preview(name = "2_fr-FR_Dark_sevenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_fr-FR_Light_tenInchScreenshots", locale = "fr", device = "id:pixel_tablet")
@Preview(name = "2_fr-FR_Dark_tenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_ja-JP_Light_phoneScreenshots", locale = "ja")
@Preview(name = "2_ja-JP_Dark_phoneScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_ja-JP_Light_sevenInchScreenshots", locale = "ja", device = "id:Nexus 7")
@Preview(name = "2_ja-JP_Dark_sevenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_ja-JP_Light_tenInchScreenshots", locale = "ja", device = "id:pixel_tablet")
@Preview(name = "2_ja-JP_Dark_tenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_pt_Light_phoneScreenshots", locale = "pt")
@Preview(name = "2_pt_Dark_phoneScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_pt_Light_sevenInchScreenshots", locale = "pt", device = "id:Nexus 7")
@Preview(name = "2_pt_Dark_sevenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_pt_Light_tenInchScreenshots", locale = "pt", device = "id:pixel_tablet")
@Preview(name = "2_pt_Dark_tenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_ta_Light_phoneScreenshots", locale = "ta")
@Preview(name = "2_ta_Dark_phoneScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_ta_Light_sevenInchScreenshots", locale = "ta", device = "id:Nexus 7")
@Preview(name = "2_ta_Dark_sevenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_ta_Light_tenInchScreenshots", locale = "ta", device = "id:pixel_tablet")
@Preview(name = "2_ta_Dark_tenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_tr-TR_Light_phoneScreenshots", locale = "tr")
@Preview(name = "2_tr-TR_Dark_phoneScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_tr-TR_Light_sevenInchScreenshots", locale = "tr", device = "id:Nexus 7")
@Preview(name = "2_tr-TR_Dark_sevenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_tr-TR_Light_tenInchScreenshots", locale = "tr", device = "id:pixel_tablet")
@Preview(name = "2_tr-TR_Dark_tenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_uk_Light_phoneScreenshots", locale = "uk")
@Preview(name = "2_uk_Dark_phoneScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_uk_Light_sevenInchScreenshots", locale = "uk", device = "id:Nexus 7")
@Preview(name = "2_uk_Dark_sevenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_uk_Light_tenInchScreenshots", locale = "uk", device = "id:pixel_tablet")
@Preview(name = "2_uk_Dark_tenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "2_zh-CN_Light_phoneScreenshots", locale = "zh-CN")
@Preview(name = "2_zh-CN_Dark_phoneScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "2_zh-CN_Light_sevenInchScreenshots", locale = "zh-CN", device = "id:Nexus 7")
@Preview(name = "2_zh-CN_Dark_sevenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "2_zh-CN_Light_tenInchScreenshots", locale = "zh-CN", device = "id:pixel_tablet")
@Preview(name = "2_zh-CN_Dark_tenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Composable
fun TakePreviewSentenceScreenScreenShots() {
    AppTheme {
        SentenceScreenPreview()
    }
}

@PreviewTest
@Preview(name = "3_en-US_Light_phoneScreenshots")
@Preview(name = "3_en-US_Dark_phoneScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_en-US_Light_sevenInchScreenshots", device = "id:Nexus 7")
@Preview(name = "3_en-US_Dark_sevenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_en-US_Light_tenInchScreenshots", device = "id:pixel_tablet")
@Preview(name = "3_en-US_Dark_tenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_de-DE_Light_phoneScreenshots", locale = "de")
@Preview(name = "3_de-DE_Dark_phoneScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_de-DE_Light_sevenInchScreenshots", locale = "de", device = "id:Nexus 7")
@Preview(name = "3_de-DE_Dark_sevenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_de-DE_Light_tenInchScreenshots", locale = "de", device = "id:pixel_tablet")
@Preview(name = "3_de-DE_Dark_tenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_fr-FR_Light_phoneScreenshots", locale = "fr")
@Preview(name = "3_fr-FR_Dark_phoneScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_fr-FR_Light_sevenInchScreenshots", locale = "fr", device = "id:Nexus 7")
@Preview(name = "3_fr-FR_Dark_sevenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_fr-FR_Light_tenInchScreenshots", locale = "fr", device = "id:pixel_tablet")
@Preview(name = "3_fr-FR_Dark_tenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_ja-JP_Light_phoneScreenshots", locale = "ja")
@Preview(name = "3_ja-JP_Dark_phoneScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_ja-JP_Light_sevenInchScreenshots", locale = "ja", device = "id:Nexus 7")
@Preview(name = "3_ja-JP_Dark_sevenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_ja-JP_Light_tenInchScreenshots", locale = "ja", device = "id:pixel_tablet")
@Preview(name = "3_ja-JP_Dark_tenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_pt_Light_phoneScreenshots", locale = "pt")
@Preview(name = "3_pt_Dark_phoneScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_pt_Light_sevenInchScreenshots", locale = "pt", device = "id:Nexus 7")
@Preview(name = "3_pt_Dark_sevenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_pt_Light_tenInchScreenshots", locale = "pt", device = "id:pixel_tablet")
@Preview(name = "3_pt_Dark_tenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_ta_Light_phoneScreenshots", locale = "ta")
@Preview(name = "3_ta_Dark_phoneScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_ta_Light_sevenInchScreenshots", locale = "ta", device = "id:Nexus 7")
@Preview(name = "3_ta_Dark_sevenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_ta_Light_tenInchScreenshots", locale = "ta", device = "id:pixel_tablet")
@Preview(name = "3_ta_Dark_tenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_tr-TR_Light_phoneScreenshots", locale = "tr")
@Preview(name = "3_tr-TR_Dark_phoneScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_tr-TR_Light_sevenInchScreenshots", locale = "tr", device = "id:Nexus 7")
@Preview(name = "3_tr-TR_Dark_sevenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_tr-TR_Light_tenInchScreenshots", locale = "tr", device = "id:pixel_tablet")
@Preview(name = "3_tr-TR_Dark_tenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_uk_Light_phoneScreenshots", locale = "uk")
@Preview(name = "3_uk_Dark_phoneScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_uk_Light_sevenInchScreenshots", locale = "uk", device = "id:Nexus 7")
@Preview(name = "3_uk_Dark_sevenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_uk_Light_tenInchScreenshots", locale = "uk", device = "id:pixel_tablet")
@Preview(name = "3_uk_Dark_tenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "3_zh-CN_Light_phoneScreenshots", locale = "zh-CN")
@Preview(name = "3_zh-CN_Dark_phoneScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "3_zh-CN_Light_sevenInchScreenshots", locale = "zh-CN", device = "id:Nexus 7")
@Preview(name = "3_zh-CN_Dark_sevenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "3_zh-CN_Light_tenInchScreenshots", locale = "zh-CN", device = "id:pixel_tablet")
@Preview(name = "3_zh-CN_Dark_tenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Composable
fun TakePreviewDrawingWithSentenceScreenShots() {
    AppTheme {
        DrawingWithSentencePreview()
    }
}

@PreviewTest
@Preview(name = "4_en-US_Light_phoneScreenshots")
@Preview(name = "4_en-US_Dark_phoneScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_en-US_Light_sevenInchScreenshots", device = "id:Nexus 7")
@Preview(name = "4_en-US_Dark_sevenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_en-US_Light_tenInchScreenshots", device = "id:pixel_tablet")
@Preview(name = "4_en-US_Dark_tenInchScreenshots", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_de-DE_Light_phoneScreenshots", locale = "de")
@Preview(name = "4_de-DE_Dark_phoneScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_de-DE_Light_sevenInchScreenshots", locale = "de", device = "id:Nexus 7")
@Preview(name = "4_de-DE_Dark_sevenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_de-DE_Light_tenInchScreenshots", locale = "de", device = "id:pixel_tablet")
@Preview(name = "4_de-DE_Dark_tenInchScreenshots", locale = "de", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_fr-FR_Light_phoneScreenshots", locale = "fr")
@Preview(name = "4_fr-FR_Dark_phoneScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_fr-FR_Light_sevenInchScreenshots", locale = "fr", device = "id:Nexus 7")
@Preview(name = "4_fr-FR_Dark_sevenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_fr-FR_Light_tenInchScreenshots", locale = "fr", device = "id:pixel_tablet")
@Preview(name = "4_fr-FR_Dark_tenInchScreenshots", locale = "fr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_ja-JP_Light_phoneScreenshots", locale = "ja")
@Preview(name = "4_ja-JP_Dark_phoneScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_ja-JP_Light_sevenInchScreenshots", locale = "ja", device = "id:Nexus 7")
@Preview(name = "4_ja-JP_Dark_sevenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_ja-JP_Light_tenInchScreenshots", locale = "ja", device = "id:pixel_tablet")
@Preview(name = "4_ja-JP_Dark_tenInchScreenshots", locale = "ja", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_pt_Light_phoneScreenshots", locale = "pt")
@Preview(name = "4_pt_Dark_phoneScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_pt_Light_sevenInchScreenshots", locale = "pt", device = "id:Nexus 7")
@Preview(name = "4_pt_Dark_sevenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_pt_Light_tenInchScreenshots", locale = "pt", device = "id:pixel_tablet")
@Preview(name = "4_pt_Dark_tenInchScreenshots", locale = "pt", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_ta_Light_phoneScreenshots", locale = "ta")
@Preview(name = "4_ta_Dark_phoneScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_ta_Light_sevenInchScreenshots", locale = "ta", device = "id:Nexus 7")
@Preview(name = "4_ta_Dark_sevenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_ta_Light_tenInchScreenshots", locale = "ta", device = "id:pixel_tablet")
@Preview(name = "4_ta_Dark_tenInchScreenshots", locale = "ta", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_tr-TR_Light_phoneScreenshots", locale = "tr")
@Preview(name = "4_tr-TR_Dark_phoneScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_tr-TR_Light_sevenInchScreenshots", locale = "tr", device = "id:Nexus 7")
@Preview(name = "4_tr-TR_Dark_sevenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_tr-TR_Light_tenInchScreenshots", locale = "tr", device = "id:pixel_tablet")
@Preview(name = "4_tr-TR_Dark_tenInchScreenshots", locale = "tr", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_uk_Light_phoneScreenshots", locale = "uk")
@Preview(name = "4_uk_Dark_phoneScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_uk_Light_sevenInchScreenshots", locale = "uk", device = "id:Nexus 7")
@Preview(name = "4_uk_Dark_sevenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_uk_Light_tenInchScreenshots", locale = "uk", device = "id:pixel_tablet")
@Preview(name = "4_uk_Dark_tenInchScreenshots", locale = "uk", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Preview(name = "4_zh-CN_Light_phoneScreenshots", locale = "zh-CN")
@Preview(name = "4_zh-CN_Dark_phoneScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES)
@Preview(name = "4_zh-CN_Light_sevenInchScreenshots", locale = "zh-CN", device = "id:Nexus 7")
@Preview(name = "4_zh-CN_Dark_sevenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:Nexus 7")
@Preview(name = "4_zh-CN_Light_tenInchScreenshots", locale = "zh-CN", device = "id:pixel_tablet")
@Preview(name = "4_zh-CN_Dark_tenInchScreenshots", locale = "zh-CN", uiMode = Configuration.UI_MODE_NIGHT_YES, device = "id:pixel_tablet")
@Composable
fun TakePreviewSentenceScreenWithDrawingScreenShots() {
    AppTheme {
        SentenceScreenWithDrawingPreview()
    }
}

