[versions]
activityCompose = "1.13.0"
agp = "9.4.0"
compose = "1.12.0"
compose-bom = "2026.08.00"
compose-plugin = "2.4.10"
constraintlayout-compose = "1.1.2"
core = "1.7.0"
core-ktx = "1.19.0"
core-splashscreen = "1.2.0"
core-testing = "2.2.0"
datastore = "1.2.1"
graphicsShapes = "1.1.0"
junit-ktx = "1.2.0"
koin-bom = "4.2.2"
kotlin = "2.4.10"
kotlinx-serialization = "1.11.0"
ksp = "2.3.11"
ktorVersion = "3.5.2"
lifecycleViewmodelKtx = "2.11.0"
logback = "1.6.3"
material3 = "1.4.0"
mockitoAndroid = "5.23.0"
mockitoKotlin = "6.3.0"
navigation-compose = "2.10.0-alpha02"
okio = "3.18.2"
room3 = "3.0.3"
runner = "1.7.0"
screenshot = "0.0.1-alpha16"
sqlite = "2.7.1"
uiUnit = "1.12.1"
lifecycle = "2.11.0"
core-bundle = "1.0.1"
buildconfig = "6.0.10"
filekit = "0.16.0"

[libraries]
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "uiUnit" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
datastore-preferences-android = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphicsShapes" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
core-bundle = { module = "org.jetbrains.androidx.core:core-bundle", version.ref = "core-bundle" }
androidx-room3-compiler = { module = "androidx.room3:room3-compiler", version.ref = "room3" }
androidx-room3-runtime = { module = "androidx.room3:room3-runtime", version.ref = "room3" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-desktop = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-ktx" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-ktx" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-bom" }
koin-android-test = { module = "io.insert-koin:koin-android-test", version.ref = "koin-bom" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-bom" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-bom" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-bom" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-bom" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin-bom" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-bom" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorVersion" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktorVersion" }
ktor-serialization-kotlinx-cbor = { module = "io.ktor:ktor-serialization-kotlinx-cbor", version.ref = "ktorVersion" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktorVersion" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktorVersion" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktorVersion" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktorVersion" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktorVersion" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktorVersion" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktorVersion" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
screenshot-validation-api = { group = "com.android.tools.screenshot", name = "screenshot-validation-api", version.ref = "screenshot" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidx-room3 = { id = "androidx.room3", version.ref = "room3" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-plugin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "compose-plugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }